### ISSUE TITLE
Avoid using @nonnull as example?

### ISSUE THREAD

**Issue by munificent** [sigmundch/DEP-member-interceptors#2]
I think contract validation is definitely a useful example to show, but I worry that if we use `@nonnull` as the hypothetic contract that the discussion will rathole on non-nullability. I, of course, care a lot about non-nullability, but it's not relevant to _this_ proposal. :)

How about `@nonnegative` or something?

**Comment by sigmundch** [comment]
Good idea, I'll make it so.
