### ISSUE TITLE
More rationale for using annotation syntax

### ISSUE THREAD

**Issue by munificent** [sigmundch/DEP-member-interceptors#8]
To me, the biggest reason to use annotation syntax for interceptors is that it lets a library _encapsulate_ the usage of interception. My awesome framework may use `@foo` as a regular annotation in 1.2.3 and then switch to making `@foo` an interceptor in 1.3.0 without breaking my users or even requiring them to know.

**Comment by sigmundch** [comment]
good point, I added this to the proposal document too.
